### ISSUE TITLE
feat: cref implementation

### ISSUE THREAD

**Issue by inftord** [OoLunar/DocBot#1]
my current idea for crefs implementation is basically:
make crefs work like a command that you can copy

**Comment by OoLunar** [comment]
To add missing context:

Discord recently added extended support for markdown. This includes headers and more specifically: hyperlinks. Additionally, Discord has had support for executing slash commands via copying (see image below.)

![image](https://github.com/OoLunar/DocBot/assets/46751150/c0c37a64-df71-471d-8658-254d60b58718)

The idea here is to combine the two features to easily allow viewing other documentation referenced by `cref` in the XML docs.

- To create a hyperlink in Discord is the same as creating a hyperlink in markdown:
  \[brackets with text inside\]\(http://parenthesis.url)
- To create a clickable slash command, simply embed the slash command name with the slash command id:
  `</about:1039719636058513434>`
  
Using the methods above, we can combine the two to create text like the following:

\[`/documentation member:SendMessageAsync(string? content)`\]\(</documentation:1039719636058513434>)

which would render like such:

[`/documentation member:SendMessageAsync(string? content)`](https://github.com/OoLunar/DocBot/issues/1)

**Comment by inftord** [comment]
24 minutes later:
it doesn't work, thanks discord

**Comment by OoLunar** [comment]
After further investigation, we've discovered the following:

- You cannot hyperlink slash commands:
![image](https://github.com/OoLunar/DocBot/assets/46751150/b0fe2fe4-7a90-48aa-8ebe-9ea3769e9f39)

- You cannot add arguments to slash commands:
![image](https://github.com/OoLunar/DocBot/assets/46751150/34da64f3-4dc2-4eda-aa09-d0dc2fd8bc76)

This makes this feature fundamentally impossible without changes from Discord. This issue will be reopened if Discord ever adds support for both of the above features.
